#import "@preview/arkheion:0.1.1": arkheion, arkheion-appendices

#show: arkheion.with(
  title: "Flashlight Project Proposal",
  authors: (
    (name: "Ahmad Taka", email: "ahmadtak@mit.edu", affiliation: "MIT EECS"),
  ),
  // Insert your abstract after the colon, wrapped in brackets.
  // Example: `abstract: [This is my abstract...]`
  date: "October 28, 2025",
)
#set cite(style: "chicago-author-date")
#show link: underline

= Summary
cd

= Hardware and System Diagram

#figure(
  image("figures/block_diagram.png", width: 120%),
  caption: [Block diagram of the flashlight system, showing power and control subsystems.],
) <figuren>

This block diagram outlines the overall flashlight system, including power input, sensing, and control subsystems. For the final project, the primary focus is on the Boost Converter block, shown as the section responsible for stepping up the voltage and providing constant-current regulation to drive the Cree XHP50.3 LED. The converter senses output current through a shunt resistor and feeds this information back to maintain stable LED brightness across varying input voltages.

This design is an initial draft architecture, where only the boost stage will be developed, tested, and characterized within the current project scope. Future integration with the STM32-based logic, sensors, and battery management circuitry will come later. A key part of this phase is evaluating whether GaN FETs or traditional silicon MOSFETs offer better performance in terms of thermal handling, switching frequency, and overall circuit footprint for the synchronous boost topology.


== Initial Boost Design with Feedback

#figure(
  image("figures/boost.png", width: 100%),
  caption: [Schematic of the synchronous boost converter.],
) <figuren>

#figure(
  image("figures/current_sense.png", width: 100%),
  caption: [Schematic of the current sensing and feedback network.],
) <figuren>

This initial design uses a version of the boost converter in Lab 2, a high-current, 
non-synchronous boost converter, as the main power stage that steps the input
voltage (3–4.3 V) up above the 5.6 V (forward-voltage) required by the Cree XHP50.3 LED. 
However unlike the lab, the conververter operates in current-mode control. The LED 
current is sensed through a high-side shunt resistor, whose voltage drop represents 
the real-time LED current. The high-side placement of the shunt allows for accurate current measurement
without interfering with the LED ground reference. 

That sense voltage feeds into a dual op-amp circuit configured as a differential 
amplifier and comparator. The amplifier conditions the shunt voltage and compares 
it against a reference voltage generated by a potentiometer. By adjusting 
the potentiometer, the reference voltage changes, effectively controlling 
the output current setpoint. The op-amp’s output is routed through a variable duty 
cycle control circuitry where the duty cyvle can range from 0.5 to 0.85 to maintain 
the desired LED current.

In summary, the system forms a closed-loop constant-current boost converter, where 
the boost stage supplies the main power conversion, and the op-amp plus digital
potentiometer network provides adjustable current regulation.


== GaN Vs Tradional FETs

GaN lets you push ~3× higher switching frequency, which cuts L or output cap size by 
~3× and lowers total FET heat at this power. Silicon at lower fSW pays more in switching 
and gate-drive loss, so even with similar RDS(on), total FET loss is higher.
Although not a fair comparison the table below shows how a QFN GaN Chip (EPC2302) 
stacks up against a larger, older Si FET (IRF540N) in this application. 
Estimates below isolate the power switches only and ignores how the gate is driven. 

\
#figure(
  table(
    align: center,
      columns: (auto, auto, auto),
      row-gutter: (2pt, auto),
      stroke: 0.5pt,
      inset: 5pt,

    [*Parameter*], [*Si FET \ (IRF540N)*], [*GaN FET \ (EPC2302)*],
    [fSW (MHz)], [0.4], [1.2],
    [L (µH), Vin=3.3V], [2.27], [0.76],
    [RDS(on) (mΩ)], [44], [3.8],
    [Qg·Vg (nC·V)], [630], [40],
    [Switching (W)], [0.79], [0.12],
    [Gate-drive loss (W)], [0.50], [0.10],
    [Total loss (W)], [1.29], [0.22],
    [Size note], [Baseline], [~3× smaller L/C],
  ),
  caption: [Table comparing estimated losses and component sizes between Silicon and GaN FETs in the boost converter application.],
) <table>
= Special Components and BOM 


*TC4426* High-speed Low side driver for the GaN FET. 

*Current-sense shunt R1 = 10 mΩ* Sets LED current for the op-amp loop. Requires Kelvin sense. 

#figure(
  table(
    align: center,
      columns: (auto, auto, auto),
      row-gutter: (2pt, auto),
      stroke: 0.5pt,
      inset: 5pt,

      [*Part*], [*Quantity*], [*Price \$*],
      [TC4426 (Sync Boost IC, U6)], [1], [2.20],
      [Shunt Resistor 10 mΩ (R1)], [1], [0.54],
      [EPC2302 eGaN FET], [10], [34.58],
      [INA180A1 (Current-Shunt Amp, U8)], [1], [-],
      [Cree XHP50.3 HD 6 V LED (D3)], [5], [37.95],
  ),
  caption: [Bill of materials excerpt highlighting the essential boost IC, sense shunt, GaN option (EPC2302), and notable system parts used in the flashlight driver],
) <table>


= Project Scope and Management

For this project, I will focus on designing, building, and testing the boost converter 
stage with constant-current feedback to drive the Cree XHP50.3 LED. I will also design
two other supplies to explore the use of alternate power converters. The first is the 
same boost topology however with GaN FETts to compare performance and thermal 
characteristics against the traditional silicon FET design. The second is a
small switched-capacitor voltage doubler to create high-voltage pulses for the
LED, building on the switched-capacitor concepts from Lab 3. 

In the first phase, I’ll build a basic prototype using the Totem Board 
from Lab 4 and a 250 kHz switching circuit with current feedback,
implemented entirely in analog. This setup will build directly on the work from 
Lab 3, where I developed and tested the fundamental switching and sensing stages. 
The goal is to verify that the constant-current feedback loop operates as expected 
before integrating the full boost converter. Once the analog prototype is stable,
I’ll measure temperature rise and efficiency across different loads and input 
voltages to guide the final design.

In the second phase, I’ll build a GaN-based version of the boost converter to compare
performance. Using GaN FETs should allow higher switching frequencies, reducing inductor/capacitor
size and improving thermal performance. I’ll follow a similar testing procedure to 
evaluate efficiency and heat dissipation.

Finally, I’ll design and test a switched-capacitor voltage doubler to create short,
high-voltage pulses for the LED. This stage will explore how pulsed operation 
affects brightness and thermal characteristics, building on the switched-capacitor
concepts from Lab 3.

= Timetable

- *Week starting Nov 10*: Lock in Schematic and design choices. Finalize BOM and order parts (DONE).

- *Week starting Nov 17*: Began modeling and circuit construction (IN PROGRESS).

- *Week starting Nov 24*: Design mechanical enclosure. Make GaN version and switch-cap version.

- *Week starting Dec 1*: Test Boards and integrate into system.

- *Week starting Dec 8*: Show off flashlight.

// = Math

// *Inline:* Let $a$, $b$, and $c$ be the side
// lengths of right-angled triangle. Then, we know that: $a^2 + b^2 = c^2$

// *Block without numbering:*

// #math.equation(block: true, numbering: none, [
//   $
//     sum_(k=1)^n k = (n(n+1)) / 2
//   $
// ])

// *Block with numbering:*

// As shown in @equatisudo on.

// $
//   sum_(k=1)^n k = (n(n+1)) / 2
// $ <equation>

// *More information:*
// - #link("https://typst.app/docs/reference/math/equation/")


// = Citation

// You can use citations by using the `#cite` function with the key for the reference and adding a bibliography. Typst supports BibLateX and Hayagriva.

// ```typst
// #bibliography("bibliography.bib")
// ```

// Single citation @Vaswani2017AttentionIA. Multiple citations @Vaswani2017AttentionIA @hinton2015distilling. In text #cite(<Vaswani2017AttentionIA>, form: "prose")

// *More information:*
// - #link("https://typst.app/docs/reference/meta/bibliography/")
// - #link("https://typst.app/docs/reference/meta/cite/")

// = Figures and Tables


// #figure(
//   table(
//     align: center,
//     columns: (auto, auto),
//     row-gutter: (2pt, auto),
//     stroke: 0.5pt,
//     inset: 5pt,
//     [header 1], [header 2],
//     [cell 1], [cell 2],
//     [cell 3], [cell 4],
//   ),
//   caption: [#lorem(5)],
// ) <table>

// #figure(
//   image("image.jpg", width: 30%),
//   caption: [#lorem(7)],
// ) <figuren>

// *More information*

// - #link("https://typst.app/docs/reference/meta/figure/")
// - #link("https://typst.app/docs/reference/layout/table/")

// = Referencing

// @figuren #lorem(10), @table.


// *More information:*

// - #link("https://typst.app/docs/reference/meta/ref/")

// = Lists

// *Unordered list*

// - #lorem(10)
// - #lorem(8)

// *Numbered list*

// + #lorem(10)
// + #lorem(8)
// + #lorem(12)

// *More information:*
// - #link("https://typst.app/docs/reference/layout/enum/")
// - #link("https://typst.app/docs/reference/meta/cite/")


// // Add bibliography and create Bibiliography section
// #bibliography("bibliography.bib")

// // Create appendix section
// #show: arkheion-appendices
// =

// == Appendix section

// #lorem(100)

