M48
; DRILL file {KiCad 8.0.8} date 2025-02-16T18:34:08-0500
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-16T18:34:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0266
%
G90
G05
T1
X4.1632Y-5.2386
T2
X4.1632Y-4.9551
M30
