M48
; DRILL file {KiCad 8.0.8} date 2025-03-20T23:22:12-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-20T23:22:12-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.8
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0266
%
G90
G05
T1
X3.7872Y-3.7986
T2
X3.7872Y-3.5151
M30
